name: Try repro cases

on: push

jobs:
  try:
    name: Try repro cases
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node dependencies
        run: |
          npm install @actions/tool-cache

      - name: Add CodeQL CLI to PATH
        uses: actions/github-script@v7
        with:
          script: |
            const path = require(`path`);
            const tc = require(`@actions/tool-cache`);

            const codeQLPath = await tc.find(`CodeQL`, `*`);
            core.addPath(path.join(codeQLPath, `codeql`));

      - name: Install Clang 19 from tip-of-tree
        env:
          LLVM_SH: ${{ runner.temp }}/llvm.sh
        run: |
          curl https://apt.llvm.org/llvm.sh -o "${LLVM_SH}"
          chmod +x "${LLVM_SH}"
          sudo "${LLVM_SH}" 19

      - name: Show tool versions
        run: |
          which clang-19
          clang-19 --version

          which codeql
          codeql --version

      - name: Build database
        env:
          CODEQL_DB: ${{ runner.temp }}/test-cc
        run: |
          codeql database init "${CODEQL_DB}" --source-root=${PWD} --language=cpp
          for f in test*.c*; do
            codeql database trace-command -- "${CODEQL_DB}" clang-19 "${f}" -c -o /dev/null
          done
          codeql database finalize "${CODEQL_DB}"

      - name: Print extractor logs
        env:
          CODEQL_DB: ${{ runner.temp }}/test-cc
        run: |
          for logfile in $(find "${CODEQL_DB}/log/extractor" -name '*.log'); do
            echo -n "::group::"
            # guess at the input filename from the log file
            egrep --only-matching --max-count=1 'test[a-z0-9]*\.c[a-z]*' "${logfile}"

            cat "${logfile}"

            echo "::endgroup::"
          done

#
