name: Try repro case

on: push

jobs:
  try:
    name: Try repro case
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Clang tip-of-tree
        run: |
          curl https://apt.llvm.org/llvm.sh -o /tmp/llvm.sh
          chmod +x /tmp/llvm.sh
          sudo /tmp/llvm.sh 19

      - name: Show versions
        run: |
          clang-19 --version
          codeql --version

#
