name: Try repro case

on: push

jobs:
  try:
    name: Try repro case
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node dependencies
        run: |
          npm install @actions/tool-cache

      - name: Add CodeQL CLI to PATH
        uses: actions/github-script@v7
        with:
          script: |
            const path = require(`path`);
            const tc = require(`@actions/tool-cache`);

            const codeQLPath = await tc.find(`CodeQL`, `*`);
            core.addPath(path.join(codeQLPath, `codeql`));

      - name: Install Clang 19 from tip-of-tree
        run: |
          curl https://apt.llvm.org/llvm.sh -o /tmp/llvm.sh
          chmod +x /tmp/llvm.sh
          sudo /tmp/llvm.sh 19

      - name: Show versions
        run: |
          which clang-19
          clang-19 --version

          which codeql
          codeql --version

#
